config/routes.rb
Stacks::Application.routes.draw do

  namespace :api do
    resources :thumbs_up,
      :only => [:create, :destroy],
      :controller => 'thumbs_up',
      :defaults => { :format => 'json' }

    resources :item,
      :only => [:create],
      :controller => 'item',
      :defaults => { :format => 'json' }
  end

  match "item/:id" => "uri_item#show", :id => /\d+/, as: 'uri_item'

  get "/services/index" => "services#index"

  devise_for :user,
    :path_names => {
      :sign_up  => "signup",
      :sign_in  => "signin",
      :sign_out => "signout"
    },
    :controllers => {
      :omniauth_callbacks => "service/callback"
    }

  root :to => 'top#index'

  get "top/index"
  get "timeline/index"

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if user_signed_in?
      @items = current_user.uri_items()
    else
      @items = UriItem.order("created_at").limit(20).all()
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/_comment.html.slim
.comment
  .comment-icon
    a href="#"
      img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-snc4/186035_897940273_1597318_q.jpg" width="32" height="32" alt=""
  .comment-content
    .comment-name
      a href="#" #{comment.user.name}
    .comment-text
      = comment.text
    .comment-at
      = distance_of_time_in_words_to_now(comment.created_at) + " ago"

app/views/top/_item.html.slim
.unit
  - collapse_id = "accordion-#{item.id}"

  .storyUnit id="#{item.id}"
    .titleUnit
      a href="#{item.url}" target="_blank"
        img src="#{item.favicon_url}" width="24" height="24" alt=""
        | &nbsp;
        span.title #{item.title}

    .actionUnit
      = render "item_action_menu", item: item, collapse_id: collapse_id

    .collapse id="#{collapse_id}"
      .commentUnit
        - item.comments.each do |comment|
          = render "comment", comment: comment
        .comment.more
          span
            a href="#{url_for(uri_item_path(item.id))}" more

app/views/top/_item_action_menu.html.slim
div
  span.btn-group data-toggle="button"
    button.btn.btn-small.thumbsUp class=(user_signed_in? ? '' : 'disabled') type="button" rel="tooltip" title="thumbs up if you like this !" data-thumbsupid="#{thumbs_up_id(item)}" data-uri="#{item.url}" data-loading-text="..."
      i.icon-thumbs-up
      | good !

  span.btn-group data-toggle="button"
    - has_comments = item.comments.empty?

    button.btn.btn-small class=(has_comments ? 'disabled' : '') data-toggle="collapse" type="button" rel="tooltip" title="comments" data-target=(has_comments ? '' : "##{collapse_id}")
      i.icon-comment-alt
      span.comment_size
        | &nbsp;#{item.comments.size}&nbsp;

  span.btn-group
    button.btn.btn-small type="button" rel="tooltip" title="share this site."
      i.icon-share
      | share
    button.btn.btn-small type="button" rel="tooltip" title="view original site."
      i.icon-file-alt
      | view original

app/views/top/index.html.slim
- unless current_user()
  = render :partial => 'layouts/brand'

.container
  .row
    .span12
      ol.items
        - @items.each do |item|
          li.item
            = render 'item', :item => item

= content_for :javascript
  = javascript_include_tag 'api/thumbs_up'