config/routes.rb
Stacks::Application.routes.draw do

  namespace :api do
    resources :thumbs_up,
      :only => [:create, :destroy],
      :controller => 'thumbs_up',
      :defaults => { :format => 'json' }

    resources :item,
      :only => [:create],
      :controller => 'item',
      :defaults => { :format => 'json' }
  end

  match "item/:id" => "uri_item#show", :id => /\d+/, as: 'uri_item'

  get "/services/index" => "services#index"

  devise_for :user,
    :path_names => {
      :sign_up  => "signup",
      :sign_in  => "signin",
      :sign_out => "signout"
    },
    :controllers => {
      :omniauth_callbacks => "service/callback"
    }

  root :to => 'top#index'

  get "top/index"
  get "timeline/index"

end

app/views/layouts/_brand.html.slim
.container.brand
  .row
    .span8.offset2
      h1
        | stacks
      p
        | Share sites with your friends.
      p
        a href="#" link

app/views/layouts/_footer.html.slim
footer
  .container
    .row
      .span3
        h4 about
        ul.unstyled
          li
            a href="#" rel="tooltip" title="Introduction about this service."
              | this site
          li
            a href="#" rel="tooltip" title="HowTos about this serivce."
              | How To
          li
            a href="#" rel="tooltip" title="I wanna drink more beer. cheers!"
              | Donate

      .span3
        h4 developers
        ul.unstyled
          li
            a href="#" rel="tooltip" title="about WebAPI to use this service."
              | API(not yet..)

      .span3
        h4 policy
        ul.unstyled
          li
            a href="#" rel="tooltip" title="term of services"
              | terms
          li
            a href="#" rel="tooltip" title="privacy policy"
              | privacy policy

      .span3
        h4 news
        ul.unstyled
          li
            a href="#" rel="tooltip" title="this service blog's rss feed"
              i.icon-rss news
          li
            a href="#" rel="tooltip" title="facebook page"
              i.icon-facebook facebook
          li
            a href="#" rel="tooltip" title="google+ page"
              i.icon-google-plus-sign google+
          li
            a href="#" rel="tooltip" title="twitter account"
              i.icon-twitter twitter
    .row
      .offset2.span10
      ul.unstyled
        li.description
          | Made by hirakiuc@gmail.com
        li.description
          | Based on ruby 1.9.3, rails3, Twitter Bootstrap, facebook like timeline.

app/views/layouts/_modal_signin.html.slim
#modal-signin.modal.hide.fade tabindex="-1" role="dialog" aria-labelledby="modal-signin" aria-hidden="true"
  .modal-header
    button.close type="button" data-dismiss="modal" aria-hidden="true"
      | &times;
    h3 SignIn
  .modal-body
    .container
      .row
        .span3
          form.form-vertical accept-charset="utf-8" action="#" autocomplete="off" method="post"
            fieldset
              input type="text" id="user[email]" placeholder="Email Address"
              br
              input type="password" id="user[passwd]" placeholder="Password"
              p
              button.btn type="submit" SignUp
        .span3
          div
            a href="#" class="signin-button twitter"
              i
              span Sign In with twitter
          div
            a href="#" class="signin-button facebook"
              i
              span Sign In with Facebook
          div
            a href="#" class="signin-button googleplus"
              i
              span Sign In with Google+

  .modal-footer
    a.btn href="#" data-dismiss="modal" aria-hidden="true" Close

app/views/layouts/_modal_signup.html.slim
#modal-signup.modal.hide.fade tabindex="-1" role="dialog" aria-labelledby="modal-signup" aria-hidden="true"
  .modal-header
    button.close type="button" data-dismiss="modal" aria-hidden="true"
      | &times;
    h3 SignUp
  .modal-body
    .container
      .row
        .span3
          form.form-vertical accept-charset="utf-8" action="#" autocomplete="off" method="post"
            fieldset
              input type="text" id="user[email]" placeholder="Email Address"
              br
              input type="text" id="user[name]" placeholder="Name"
              br
              input type="password" id="user[passwd]" placeholder="Password"
              p
              a.btn href="#" SignUp
        .span3
          div
            a href="#" class="signin-button twitter"
              i
              span Sign Up with twitter
          div
            a href="#" class="signin-button facebook"
              i
              span Sign Up with Facebook
          div
            a href="#" class="signin-button googleplus"
              i
              span Sign Up with Google+
  .modal-footer
    a.btn href="#" data-dismiss="modal" aria-hidden="true" Close

app/views/layouts/_navbar.html.slim
.navbar.navbar-fixed-top
  .navbar-inner
    ul.nav
      li
        a href="#" Home
      li.divider-vertical
      li.dropdown
        a.dropdown-toggle href="#" data-toggle="dropdown"
          | test2
          b.caret
        ul.dropdown-menu
          li
            a href="#" test2-menu1
          li
            a href="#" test2-menu2
      li.divider-vertical
      li
        a href="#" test3

    ul.nav.pull-right
      - if user_signed_in?
        li
          = form_for UriItem.new, :url => api_item_index_path, :html => { :class => "navbar-form" } do |f|
            = f.url_field :url, :required => true, :html => { :class => "input-small" }
            = f.button "submit", :disable_with => "..."

        li.dropdown
          a.dropdown-toggle href="#" data-toggle="dropdown"
            | #{current_user().name}
            b.caret
          ul.dropdown-menu
            li
              = link_to('SignOut', destroy_user_session_path, :method => :delete)
      - else
        li#signup-btn
          = link_to('SignUp', new_user_registration_path, :class => 'btn btn-small')
        li#signin-btn
          = link_to('SignIn', new_user_session_path, :class => 'btn btn-small')

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Stacks"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag params[:controller]
    / = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  body
    = render :partial => 'layouts/navbar'

    .container
      .row
        .span12
          = bootstrap_flash

    = yield

    = render :partial => 'layouts/footer'

    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = javascript_include_tag params[:controller]